### ISSUE TITLE
I-VT classification is being done wrong.

### ISSUE THREAD

**Issue by AlfredLTennyson** [DiGyt/cateyes#6]
Hello, i have used I-VT classification algorithm from cateyes. 
The output of it is wrong. 
Here i am attaching the graph. 
Kindly Help me.
![image](https://user-images.githubusercontent.com/114279791/195917872-1d14f791-2338-431e-abf2-a145187187d7.png)

**Comment by AlfredLTennyson** [comment]
https://github.com/AlfredLTennyson/eye_gaze_data_for_1_trial/blob/main/Untitled8.ipynb
This is the colab file.

**Comment by DiGyt** [comment]
Hey there @AlfredLTennyson ,

Thanks for trying cateyes and for bringing this to my attention.
In fact, there seemed to a indexing error, which I now fixed. Now, your application of `classify_velocity` should return this:
![unfiltered](https://user-images.githubusercontent.com/34550289/197398189-b4e9ce7c-72c2-468d-98a3-952455c8d50d.png)
To further reduce noise, You can apply a simple median boxcar filter, e.g. by using:
```python
boxcar_samples = 3
dataframe[["0", "1"]] = dataframe[["0", "1"]].rolling(boxcar_samples).median()
```
Which would result in this:
![boxcar_filtered](https://user-images.githubusercontent.com/34550289/197398297-1aa4c7c5-4f8a-4da4-a2c3-ec59116d8f2c.png)


Also note that you could use the private function `_get_time` to create a sampling times array from the sampling rate:
```python
from cateyes.utils import _get_time

sampling_rate = 1000
times, sampling_rate = _get_time(dataframe, sampling_rate)
```

Hope this helps :)

If not, feel free to reopen...
